<html>
    <head>
        <title>PHP version</title>
    </head>
    <body>
        <div style="text-align: center; font: 14px/1.35em arial,helvetica,sans-serif;">
            <div style="margin:0 0 25px 0; border-bottom:1px solid #ccc;">
                <h3 style="font-size: 1.7em; font-weight: normal; text-transform: none; color: rgb(47, 47, 47); text-align: center; margin: 100px 0px;">Whoops, it looks like you have an invalid PHP version.
                </h3>
            </div>
            <p>Factory Package supports PHP 5.3.2 or newer.</p><p>
            </p>
        </div>   
    </body>
</html>
