<div id="main-content">
    
     <?php echo $this->render('common/messager.phtml') ?>
    
    <div class="operation-wrapper">        
        <a href="<?php echo $this->refresh_ ?>" class="btn ajax"><i class="icon-refresh"></i> <?php echo ucfirst($this->t('refresh')) ?></a>
        <a onclick="print_page()" class="btn print-btn"><i class="icon-file"></i> <?php echo ucfirst($this->t('print')) ?></a>                    
        <span class="submit-btn">

            <a id="validate" class="btn btn-primary"><i class="icon-ok-sign icon-white"></i> <?php echo ucfirst($this->t('submit')) ?></a>                    
        </span>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <ul class="nav nav-list">
                <li class="nav-header">
                    <?php echo ucfirst($this->t('gestion')) ?> <?php echo $this->t($this->nameController) ?>
                </li>
                <li class="active">
                    <a href="#"><i class="icon-th-list"></i><?php echo ucfirst($this->t($this->nameController)) ?></a>
                </li>
            </ul>

        </div>
        <div class="span9"><?php echo $this->form ?></div>
    </div>
</div>