<div class="link-top-content-right">
    <a  href="<?php echo $this->url('admin', array("controller" => "index")); ?>" class="btn print-btn"><i class="icon-user"></i> <?php echo ucfirst($this->t('user')) ?></a>                    
    <a href="<?php echo $this->url('admin', array("controller" => "role")); ?>" class="btn"><i class="icon-flag"></i> <?php echo ucfirst($this->t('role')) ?></a>
    <a href="<?php echo $this->url('admin', array("controller" => "permission")); ?>" class="btn"><i class="icon-check"></i> <?php echo ucfirst($this->t('permission')) ?></a>
</div>