<div id="top-content">
    <div class ="link-top-content">
        <h1><?php echo ucfirst($this->t($this->nameController)) ?></h1>
        <span><a href="<?php echo $this->base ?>" class="btn ajax "><i class="icon-refresh"></i>  <?php echo ucfirst($this->t("refresh")) ?></a></span>
        <span><a class="btn btn-primary validate dell_button"><i class="icon-ok-sign icon-white"></i>  <?php echo ucfirst($this->t("submit")) ?></a></span>
    </div>
    <?php echo $this->render('common/top-content-right.phtml') ?>
</div>

<div id="main-content">

    <?php echo $this->render('common/messager.phtml') ?>

    <form  class="table-form form" method="post" action="<?php echo $this->addLink ?>" enctype="application/x-www-form-urlencoded">

        <table class="table table-striped table-bordered">
            <colgroup>
                <col width="5%">
                <col width="5%">
                <?php foreach ($this->role_paginator_ as $value) : ?>
                    <col width="1%">
                <?php endforeach ?>
            </colgroup>
            <thead>
                <tr class="headings">
                    <th><?php echo ucfirst($this->t('ressource')) ?></th>
                    <th><?php echo ucfirst($this->t('action')) ?></th>

                    <?php foreach ($this->role_paginator_ as $value) : ?>
                        <th><?php echo ucfirst($value['name']) ?></th>
                    <?php endforeach ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->list as $module => $ressource) : ?>
                    <tr  >
                        <td colspan="100" class="headings-break" >
                            <span class="name" ><b><?php echo ucfirst($module) ?></b></span>
                        </td>
                    </tr>

                    <?php foreach ($ressource as $key_ressource => $row) : ?>
                        <?php
                        $row['ressource'] = ($row['ressource'] == 'index') ? 'home' : $row['ressource'];
                        $row['action'] = ($row['action'] == 'index') ? 'home' : $row['action']
                        ?>
                        <tr >
                            <td>
                                <span class="element-ressource" ><?php echo ucfirst($this->t($row['ressource'])) ?></span>
                            </td> 
                            <td>
                                <span class="element-action" ><?php echo ucfirst($this->t($row['action'])) ?></span>
                            </td> 

                            <?php foreach ($this->role_paginator_ as $key => $val) : ?>
                                <?php
                                $conditions = null;
                                $relation_role_permission_model = App_Ressource::getModel('admin/relation_permission');
                                $where = $relation_role_permission_model->getAdapter()
                                        ->quoteInto('permission_id = ?', $row['permission_id']);
                                $conditions['where'][] = $where;

                                $where = $relation_role_permission_model->getAdapter()
                                        ->quoteInto('role_id = ?', $val['role_id']);
                                $conditions['where'][] = $where;
                                $rows = $relation_role_permission_model->findAll($conditions);
                                ?>
                                <td>
                                    <?php if ($val['role_id'] == 1): ?>
                                        <input type="hidden" class="checkbox-element" name="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>" value="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>">                      
                                        <input checked="checked" disabled type="checkbox" class="checkbox-element" name="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>" value="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>">                
                                    <?php else: ?>
                                        <?php if (!empty($rows)): ?>
                                            <input checked="checked" type="checkbox" class="checkbox-element" name="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>" value="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>">                      
                                        <?php else: ?>
                                            <input type="checkbox" class="checkbox-element" name="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>" value="<?php echo $row['permission_id'] ?>-<?php echo $val['role_id'] ?>">
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
                            <?php endforeach ?>
                        </tr> 
                    <?php endforeach ?> 

                <?php endforeach ?>
            </tbody>
        </table>
    </form>
</div>
